### PR TITLE
Main function usable from any code

### PR DESCRIPTION
**Pull request by 00sapo**
not tested, but it should be almost correct.

In this way, one can just call the `execute` function and run hypermax from code instead of cli

### CODE REVIEW

**Comment by 00sapo** [comment]
Little error found! Is it possible to update this pull request?

**Comment by genixpro** [comment]
I think you just push additional commits and they will be added into the pull request automatically.

**Comment by 00sapo** [comment]
Tested both from cli and from code. From code, you can call `hypermax.cli.execute`

**Comment by genixpro** [comment]
merged

**Pull request merged**
